server:
  port: 8000
  error:
    include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/transactional-guard
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    output:
        ansi:
            enabled: always


    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 200MB

app:
  base-uri: http://localhost:8000

logging:
    file:
        name: loggers.log
    level:
      root: info

monnify:
    apiKey: MK_TEST_X4YMHGLYAK
    secretKey: W39PR966TRVS3HZ403Q72J9GFC3THQ4J
    contractCode: 3955607117
    uri: https://sandbox.monnify.com



