server:
    port: 8000
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/transactional-guard
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    output:
        ansi:
            enabled: always


logging:
    file:
        name: loggers.log
    level:
      root: info

monnify:
    apiKey: MK_TEST_X4YMHGLYAK
    secretKey: W39PR966TRVS3HZ403Q72J9GFC3THQ4J
    contractCode: 3955607117
    uri: https://sandbox.monnify.com



